// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFutBTy_Xf-rlag4Q19C0rUria4DiPZns',
    appId: '1:299250748346:web:9930f2efb6c1fd9576eb83',
    messagingSenderId: '299250748346',
    projectId: 'vildi-2492e',
    authDomain: 'vildi-2492e.firebaseapp.com',
    storageBucket: 'vildi-2492e.appspot.com',
    measurementId: 'G-GMYMM1T8KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3O6u6VOrtKHjSBW2NpuAkYz8DEAVCpE8',
    appId: '1:299250748346:android:94b8823dc322e88376eb83',
    messagingSenderId: '299250748346',
    projectId: 'vildi-2492e',
    storageBucket: 'vildi-2492e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2HuMdHPhTnKR7-sUOM9UIjCsv-875uHg',
    appId: '1:299250748346:ios:b8bc33a993bc094f76eb83',
    messagingSenderId: '299250748346',
    projectId: 'vildi-2492e',
    storageBucket: 'vildi-2492e.appspot.com',
    iosClientId: '299250748346-72h84fb17u6r62s4nrai2vk4eav200ee.apps.googleusercontent.com',
    iosBundleId: 'com.ncamson.vildi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2HuMdHPhTnKR7-sUOM9UIjCsv-875uHg',
    appId: '1:299250748346:ios:b8bc33a993bc094f76eb83',
    messagingSenderId: '299250748346',
    projectId: 'vildi-2492e',
    storageBucket: 'vildi-2492e.appspot.com',
    iosClientId: '299250748346-72h84fb17u6r62s4nrai2vk4eav200ee.apps.googleusercontent.com',
    iosBundleId: 'com.ncamson.vildi1',
  );
}
